### ISSUE TITLE
Тестовое задание

### ISSUE THREAD

**Issue by tseylerd** [tseylerd/student-practice-spring-2018#1]
Реализовать консольную утилиту [tee](https://en.wikipedia.org/wiki/Tee_(command)). Язык программирования на ваш выбор, но предпочтительно Java/Kotlin. Рекомендуется приложить скрипт для сборки.

Ссылку на решение и вопросы оставляйте в комментариях.

**Comment by AlexVolkow** [comment]
Волков Александр(alexander.volkow@gmail.com)

https://github.com/AlexVolkow/MyTee/

 Build script [assembly.bat](https://github.com/AlexVolkow/MyTee/blob/master/assembly.bat)/[assembly.sh](https://github.com/AlexVolkow/MyTee/blob/master/assembly.sh)

**Comment by flurescein** [comment]
Камышов Владислав
flurescein@gmail.com
https://github.com/flurescein/tee

**Comment by gordeevso** [comment]
Станислав Гордеев
https://github.com/gordeevso/tee

**Comment by pestretsov** [comment]
Пестрецов Артемий
artemypestretsov@gmail.com
https://github.com/pestretsov/my-tee

**Comment by Hotckiss** [comment]
Кириленко Андрей
kirilenko_aa@mail.ru
https://github.com/Hotckiss/Tee

**Comment by anstkras** [comment]
Краснорядцева Анастасия
anstkras@gmail.com
https://github.com/anstkras/tee

**Comment by aliscafo** [comment]
Ерохина Алина
ero.alina@gmail.com
https://github.com/aliscafo/tee

**Comment by Igor-Tukh** [comment]
Тух Игорь
igor-tukh@yandex.ru
https://github.com/Igor-Tukh/Tee-implementation

**Comment by raymon-02** [comment]
Илья Орлов
2x2.4raymon@gmail.com
https://github.com/raymon-02/tee

**Comment by kostya55516** [comment]
Константин Недиков
kostya55516@gmail.com
https://github.com/kostya55516/teeJava

**Comment by vladimirrim** [comment]
Егоров Владимир
vladimirrim98@gmail.com
https://github.com/vladimirrim/sketch_test

**Comment by AnverK** [comment]
Анвер Хусаинов
hanver12@gmail.com
https://github.com/AnverK/Tee

**Comment by vasyoid** [comment]
Василий Купоросов
vasyoid@gmail.com
https://github.com/vasyoid/tee/

**Comment by egorzhdan** [comment]
Егор Ждан
egor.zhdan@gmail.com
https://github.com/egorzhdan/ktee

**Comment by MaxVortman** [comment]
Максим Шамрай
vortmanmax@gmail.com
https://github.com/MaxVortman/mytee

**Comment by dkaznacheev** [comment]
Дмитрий Казначеев
dmitry.kaznacheev@gmail.com
https://github.com/dkaznacheev/Tee

**Comment by Kseniya-Gonta** [comment]
Ксения Гонта
https://github.com/Kseniya-Gonta/Tee-utility

**Comment by LDVSOFT** [comment]
Лапшин Дмитрий
lapshin.dv@mail.ru
https://github.com/LDVSOFT/jb-sketch-test (собирать Gradle-ом)

**Comment by shishovv** [comment]
Владислав Шишов
vshov@hotmail.com
https://github.com/shishovv/csc-practice-tee
